- name: Deploy Nginx application
  hosts: all
  tasks:
    - name: Install GIT if not present
      become: yes
      yum:
        name: git
        state: present
    - name: Copy files to k8s master
      become: yes
      copy:
        src: /var/lib/jenkins/workspace/deploy_k8s/{{item}}
        dest: /home/cloud_user/deploy/{{item}}
        owner: cloud_user
        group: cloud_user
        mode: '0777'
      loop:
        - service.yml
        - deployment.yml
    - name: Create dojo Namespace
      k8s:
        name: dojo
        api_version: v1
        kind: Namespace
        state: present
    - name: Create a Deployment by reading the definition from a local file
      k8s:
        state: present
        src: /home/cloud_user/deploy/deployment.yml
        namespace: dojo
    - name: Create a Service object by reading the definition from a file
      k8s:
        state: present
        src: /home/cloud_user/deploy/service.yml
        namespace: dojo
