- name: Deploy Nginx application
  hosts: all
  tasks:
    - name: Install GIT if not present
      become: yes
      yum:
        name: git
        state: present
    - name: Create dojo Namespace
#      become: yes
      k8s:
        name: dojo
        api_version: v1
        kind: Namespace
        state: present
    - name: Create a Deployment by reading the definition from a local file
      become: yes
      k8s:
        state: present
        src: /home/kubernetes-dojo/deployment.yml
        namespace: dojo
    - name: Create a Service object by reading the definition from a file
      become: yes
      k8s:
        state: present
        src: /home/kubernetes-dojo/service.yml
        namespace: dojo
